dias = int (input ("Digite a quantidade de dias: "))
horas = int (input ("Digite a quantidade de horas: "))
minutos = int (input ("Digite a quantidade de minutos: "))
segundos = int (input ("Digite a quantidade de segundos: "))
Total = (dias * 86400) + (horas * 3600) + (minutos * 60) + (segundos)
print ("Tempo total foi de : %i" %Total )
